# Generated by Django 4.0.2 on 2022-03-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calc',
        ),
    ]
