CATEGORIES = [
        "개운죽", "관음죽", "괴마옥", "극락조화", "금전수", "녹태고", "다바나 고사리", "더피 고사리", "둥근 잎 아카시아",
        "드라세나 드라코", "드라세나 마지나타", "디지고테카 아랄리아", "떡갈잎 고무나무", "라벤더", "로즈마리", "립살리스 트리고나",
        "마란타 레우코네우라", "마오리 소포라", "마오리 코로키아", "멕시코 소철", "멜라니 고무나무", "목마가렛", "몬스테라 델리시오사",
        "몬스테라 아단소니", "몬스테라 알보 바리에가타", "무늬 푸미라", "무늬벤자민 고무나무", "미모사", "바로크 벤자민", "박쥐란", "백묘국", "베고니아",
        "벵갈 고무나무", "보스턴 고사리", "브레이니아 니보사", "블루스타 고사리", "산세베리아", "산세베리아 문샤인", "세네시오 칸디칸스",
        "소철", "수박 페페로미아", "수채화 고무나무", "스위트 바질", "스킨답서스", "스투키", "스파티필름", "사계귤", "드라세나 맛상게아나"
]

CATEGORIES_COMMON = [
    'Fungal Leaf Spots',
    'Fungal Leaf Spots',
    'Fungal Leaf Spots',
    'healthy',
    'healthy',
    'Powdery mildew',
    'healthy',
    'Fungal Leaf Spots',
    'Fungal Leaf Spots',
    'Leaf Blight',
    'healthy',
    'Fungal Leaf Spots',
    'Fungal Leaf Spots',
    'Leaf Blight',
    'healthy',
    'Bacterial Leaf Spot',
    'Bacterial Leaf Spot',
    'healthy',
    'Bacterial Leaf Spot',
    'healthy',
    'Leaf Blight',
    'Leaf Blight',
    'healthy',
    'healthy',
    'healthy',
    'Powdery mildew',
    'Leaf scorch',
    'healthy',
    'Bacterial Leaf Spot',
    'Leaf Blight',
    'Leaf Blight',
    'Fungal Leaf Spots',
    'Fungal Leaf Spots',
    'spider mite',
    'Fungal Leaf Spots',
    'virus',
    'virus',
    'healthy'
]