# Generated by Django 4.0.2 on 2022-03-10 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='분류 항목')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='질병명')),
                ('symptom', models.TextField(blank=True, null=True, verbose_name='개요 및 증상')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='원인')),
                ('precaution', models.TextField(blank=True, null=True, verbose_name='예방법')),
                ('image_url', models.URLField(blank=True, verbose_name='참고 이미지 링크')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor', models.CharField(max_length=200, verbose_name='한글 이름')),
                ('name', models.CharField(max_length=200, verbose_name='영어 이름')),
                ('rank', models.IntegerField(verbose_name='인기 순위')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 링크')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('water_cycle', models.CharField(blank=True, max_length=200, null=True, verbose_name='물 주기')),
                ('sunlight', models.CharField(blank=True, max_length=200, null=True, verbose_name='햇볕')),
                ('temperature', models.CharField(blank=True, max_length=200, null=True, verbose_name='온도')),
                ('category', models.ManyToManyField(to='plant.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='식물 이미지')),
                ('upload_at', models.DateTimeField(auto_now=True, verbose_name='파일 작성일시')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='식물 ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('score', models.IntegerField(verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='댓글 수정일시')),
                ('plant_id', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_plant', to='plant.plant', verbose_name='식물 ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
        ),
    ]
