# Generated by Django 4.0.2 on 2022-02-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('water_cycle', models.CharField(blank=True, max_length=200, null=True)),
                ('sunlight', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('shopping_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('score', models.IntegerField(verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 작성일시')),
                ('plant_id', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_plant', to='plant.plant', verbose_name='식물 ID')),
            ],
        ),
    ]
