# Generated by Django 4.0.2 on 2022-02-25 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='shopping_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('score', models.IntegerField(verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='댓글 수정일시')),
                ('plant_id', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_plant', to='plant.plant', verbose_name='식물 ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
        ),
    ]
