# Generated by Django 4.0.2 on 2022-02-25 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='댓글 수정일시'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='이미지 링크'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='kor',
            field=models.CharField(max_length=200, verbose_name='한글 이름'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='영어 이름'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='rank',
            field=models.IntegerField(verbose_name='인기 순위'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='shopping_url',
            field=models.URLField(blank=True, null=True, verbose_name='쇼핑 링크'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='햇볕'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='온도'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_cycle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='물 주기'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='유저 ID'),
        ),
    ]
