# Generated by Django 4.0.2 on 2022-02-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plant_description_plant_shopping_url_plant_sunlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
