# Generated by Django 4.0.2 on 2022-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_review_updated_at_alter_plant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='분류 항목')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='catogory',
            field=models.ManyToManyField(to='plant.Category'),
        ),
    ]
