# Generated by Django 4.0.2 on 2022-03-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_category_plant_catogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='catogory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='shopping_url',
        ),
    ]
