# Generated by Django 4.0.2 on 2022-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_rename_catogory_plant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='식물 이미지')),
                ('upload_at', models.DateTimeField(auto_now=True, verbose_name='파일 작성일시')),
            ],
        ),
    ]
