# Generated by Django 4.0.2 on 2022-03-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_email_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
