# Generated by Django 4.0.2 on 2022-03-05 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='식물 ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID'),
        ),
    ]
